### PR TITLE
Do not link against GnuTLS

### PR DESCRIPTION
**Pull request by strugee**
It's not needed for Jellyfin.

### CODE REVIEW

**Comment by strugee** [comment]
Note: I didn't actually test this since I assumed CI would. I'll do so later.

**Comment by cvium** [comment]
Why is it not needed? We do occasionally feed ffmpeg https urls

**Comment by strugee** [comment]
Oh really? When? I guess I just assumed we didn't.

**Comment by cvium** [comment]
A .strm file may contain a link and then there's Live TV providers

**Comment by strugee** [comment]
Ahhhh okay. Makes sense. Closing then, sorry for the noise!

**Pull request closed without merging**
