### PR TITLE
Rpi Support - Add handling for NV21 and YUV420P

### PR DESCRIPTION
**Pull request by Artiume**
untested.

https://github.com/jellyfin/jellyfin-ffmpeg/issues/29

https://github.com/FFmpeg/FFmpeg/commit/d61cf1b1ebc2477749d7d7825a072400ed24af9f?diff=unified

### CODE REVIEW

**Review by JustAMan — COMMENTED** [review]
We decided to not modify the source but supply patches, don't we?

**Comment by JustAMan** [comment]
Also it just came to my mind - @nvllsvm, do we apply patches when building a dockerizef version of our ffmpeg?

**Comment by andrewrabert** [comment]
We don't modify the source code directly as we don't want to maintain a fork. I find working with patch files easier in this situation.

they are applied in the Dockerfile.

**Comment by Artiume** [comment]
So how would I apply this patch exactly?

Since this patch is applied in master, should the patch itself come from their master?

**Comment by ferferga** [comment]
Can't we cherrypick the [original commit](https://github.com/FFmpeg/FFmpeg/commit/d61cf1b1ebc2477749d7d7825a072400ed24af9f#diff-bec5e20dbf17e1c989823fa841c2f8b3) that @Artiume is trying to merge? He's not making changes that could make the maintenance more dificult, what he is doing it's already in master in the official repository, but not merged to 4.2.

**Comment by Artiume** [comment]
verified build, i dont have a sample file to test the fix with though

**Comment by andrewrabert** [comment]
IMO - lets wait until upstream releases a stable version with this patch.

**Comment by JustAMan** [comment]
We already have some backports in our patches, so it shouldn't be that big of a deal. Though I'm still worried about breaking `yuv420p` colorspace...

**Comment by joshuaboniface** [comment]
@Artiume Please reimplement as a Debian package patch (though this wouldn't help the Docker build) or close it out until upstream is consistent.

**Comment by Artiume** [comment]
I'm not sure how to package it. What can we do to fix docker? @nyanmisaka do you know if the version bump is ffmpeg would fix this or is still master only?

**Comment by nyanmisaka** [comment]
> I'm not sure how to package it. What can we do to fix docker? @nyanmisaka do you know if the version bump is ffmpeg would fix this or is still master only?

It is master only as I cant find the patch in the latest stable 4.2.2.

If you switch the ffmpeg in Dockerfile.arm/arm64 to use jellyfin-ffmpeg, and then apply this patch, it should solve the problem.

This guide should be useful when making a deb patch.
https://github.com/jellyfin/jellyfin-ffmpeg/pull/28#issuecomment-591497304

**Comment by JustAMan** [comment]
> If you switch the ffmpeg in Dockerfile.arm/arm64 to use jellyfin-ffmpeg, and then apply this patch, it should solve the problem.

We should really do this ASAP, or we risk getting different ffmpeg builds in Docker and outside in the future if someone forgets about this duality.

**Comment by Artiume** [comment]
> This guide should be useful when making a deb patch.
#28 (comment)

I would need assistance in making this happen. What would be the difference between Quilt and my PR? Once the change from upstream is ready, we just remove the patch file and it removes the change? Thus we become aligned with upstream again?

**Comment by Artiume** [comment]
Ffmpeg 4.2.3 is out.
https://ffmpeg.org/download.html#releases

**Comment by dfunkt** [comment]
FFmpeg 4.3 is out and it seems to include the commit from this PR.

**Comment by joshuaboniface** [comment]
With 4.3 out, and 4.3 being merged in other PRs, I'm going to close this one.

**Pull request closed without merging**
