### PR TITLE
Add detection of DTS:X and DTS:X IMAX

### PR DESCRIPTION
**Pull request by Bond-009**
Backport of https://git.ffmpeg.org/gitweb/ffmpeg.git/commitdiff/98a4699216fbc3a4e382ba6a10026eab39b5214e

### CODE REVIEW

**Review by nyanmisaka — APPROVED** [review]
Are any subsequent changes required on the server side?

**Review by Shadowghost — APPROVED** [review]

**Comment by Bond-009** [comment]
Server changes are already done

https://github.com/jellyfin/jellyfin/pull/11772

**Comment by gnattu** [comment]
So this is for 10.10 right?

**Comment by Shadowghost** [comment]
Yes, it was merged to master after we cut 10.9.0

**Comment by mohd-akram** [comment]
> So this is for 10.10 right?

IMO this and #399 should be backported to 10.9 due to jellyfin/jellyfin#9996.

Also using it in jellyfin/jellyfin-androidtv#2893.

**Pull request merged**
