### PR TITLE
Update CI to work with new repository layout

### PR DESCRIPTION
**Pull request by joshuaboniface**
**Changes**
1. Use new path layout.
2. Add major version calculation for use in path.
3. Remove sha256sums.
4. Drop non-LTS Ubuntus from builds (matches main server builds)

**Issues**
N/A

### CODE REVIEW

**Comment by nyanmisaka** [comment]
There are two more leftovers:
https://github.com/jellyfin/jellyfin-ffmpeg/blob/a1e482c4174d7d99d3769028c92b70bb47d780c4/.github/workflows/publish.yaml#L80-L81

**Comment by nyanmisaka** [comment]
The [jellyfin-5.1](https://github.com/jellyfin/jellyfin-ffmpeg/tree/jellyfin-5.1) branch may also need to do the same thing, and we will need to maintain it for a while for backward compatibility reasons.

**Review by Shadowghost — APPROVED** [review]
Should work as intended.

**Comment by joshuaboniface** [comment]
Done and done.

I see the MacOS build is failing, but I'm not sure if that's expected or not. Otherwise, hopefully all good!

**Review by nyanmisaka — APPROVED** [review]

**Comment by nyanmisaka** [comment]
@joshuaboniface FYI we will defer adding the noble(ubu2404) build target because upstream Debian is transitioning to glib2.0, which results in some dev libs being unavailable in the non-proposed repo. Hopefully they will be available around the time ubu2404 is released.

- https://packages.qa.debian.org/g/glib2.0.html
- https://release.debian.org/transitions/html/auto-glib2.0.html
- https://packages.ubuntu.com/source/noble/harfbuzz  (gir1.2-*-2.0-dev not available)

**Comment by joshuaboniface** [comment]
Sounds good @nyanmisaka yea I avoided adding it yet for the server CI too because the .NET repo isn't available for it yet :D

**Pull request merged**
