### PR TITLE
Update docker ffmpeg to 4.3

### PR DESCRIPTION
**Pull request by Artiume**
Have not checked the codecs to see if any of them need to be updated.

### CODE REVIEW

**Review by joshuaboniface — APPROVED** [review]
Simple enough change, worth some testing.

**Comment by Artiume** [comment]
Yeah. testing it with the new hwa interface should be fairly easy

**Review by andrewrabert — CHANGES_REQUESTED** [review]
Fails to build.
```
docker build -f docker/Dockerfile . -t dev --pull --no-cache
```

```
sed 's#@@PREFIX@@#/usr/local#' ffnvcodec.pc.in > ffnvcodec.pc
install -m 0755 -d '/usr/local/include/ffnvcodec'
install -m 0644 include/ffnvcodec/*.h '/usr/local/include/ffnvcodec'
install -m 0755 -d '/usr/local/lib/pkgconfig'
install -m 0644 ffnvcodec.pc '/usr/local/lib/pkgconfig'
Removing intermediate container 626137e5385c
 ---> 55d2ffbcf0fd
Step 59/67 : RUN          DIR=/tmp/ffmpeg && mkdir -p ${DIR} && cd ${DIR} &&         curl -sLO https://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.bz2 &&         tar -jx --strip-components=1 -f ffmpeg-${FFMPEG_VERSION}.tar.bz2
 ---> Running in 91d005b7db01
Removing intermediate container 91d005b7db01
 ---> d91e0d46fe36
Step 60/67 : COPY debian/patches/*.patch /tmp/ffmpeg/
 ---> 959379a3dccf
Step 61/67 : RUN         DIR=/tmp/ffmpeg && mkdir -p ${DIR} && cd ${DIR} &&         for patch in *.patch; do             filename="$( grep '+++' ${patch} | awk '{ print $2 }' | sed 's|jellyfin-ffmpeg/||' )";             patch --verbose ${filename} ${patch};         done &&         export PLATFORM_ARGS="" &&         case "$(uname -m)" in             arm*)                 sed -i 's/ require_pkg_config libx265 x265 x265.h x265_api_get &&//' configure                 ;;             x86*)                 PLATFORM_ARGS="--enable-libaom --enable-cuvid --enable-nvenc"                 ;;         esac &&         ./configure         --disable-debug         --disable-doc         --disable-ffplay         --enable-vaapi         --enable-shared         --enable-avresample         --enable-libopencore-amrnb         --enable-libopencore-amrwb         --enable-gnutls         --enable-gpl         --enable-libass         --enable-libfreetype         --enable-libvidstab         --enable-libmp3lame         --enable-libopenjpeg         --enable-libopus         --enable-libtheora         --enable-libvorbis         --enable-libvpx         --enable-libx265         --enable-libxvid         --enable-libx264         --enable-libkvazaar         --extra-libs=-lpthread         --enable-postproc         -docker build -f docker/Dockerfile . -t dev --pull --no-cache-enable-version3         --enable-rpath         --extra-cflags="-I${PREFIX}/include"         --extra-ldflags="-L${PREFIX}/lib"         --extra-libs=-ldl         --prefix="${PREFIX}"         ${PLATFORM_ARGS} &&         make &&         make install &&         make distclean &&         hash -r &&         cd tools &&         make qt-faststart &&         cp qt-faststart ${PREFIX}/bin
 ---> Running in 68b5804f6292
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|Index: jellyfin-ffmpeg/libavformat/segment.c
|===================================================================
|--- jellyfin-ffmpeg.orig/libavformat/segment.c 2019-10-02 13:05:57.119005772 -0400
|+++ jellyfin-ffmpeg/libavformat/segment.c      2019-10-02 13:06:11.367388679 -0400
--------------------------
patching file libavformat/segment.c
Using Plan A...
Hunk #1 succeeded at 86 (offset -1 lines).
Hunk #2 succeeded at 702 (offset -1 lines).
Hunk #3 succeeded at 905 (offset -11 lines).
done
patch: libavcodec/amfenc_hevc.c: extra operand
patch: Try 'patch --help' for more information.
The command '/bin/sh -c DIR=/tmp/ffmpeg && mkdir -p ${DIR} && cd ${DIR} &&         for patch in *.patch; do             filename="$( grep '+++' ${patch} | awk '{ print $2 }' | sed 's|jellyfin-ffmpeg/||' )";             patch --verbose ${filename} ${patch};         done &&         export PLATFORM_ARGS="" &&         case "$(uname -m)" in             arm*)                 sed -i 's/ require_pkg_config libx265 x265 x265.h x265_api_get &&//' configure                 ;;             x86*)                 PLATFORM_ARGS="--enable-libaom --enable-cuvid --enable-nvenc"                 ;;         esac &&         ./configure         --disable-debug         --disable-doc         --disable-ffplay         --enable-vaapi         --enable-shared         --enable-avresample         --enable-libopencore-amrnb         --enable-libopencore-amrwb         --enable-gnutls         --enable-gpl         --enable-libass         --enable-libfreetype         --enable-libvidstab         --enable-libmp3lame         --enable-libopenjpeg         --enable-libopus         --enable-libtheora         --enable-libvorbis         --enable-libvpx         --enable-libx265         --enable-libxvid         --enable-libx264         --enable-libkvazaar         --extra-libs=-lpthread         --enable-postproc         --enable-version3         --enable-rpath         --extra-cflags="-I${PREFIX}/include"         --extra-ldflags="-L${PREFIX}/lib"         --extra-libs=-ldl         --prefix="${PREFIX}"         ${PLATFORM_ARGS} &&         make &&         make install &&         make distclean &&         hash -r &&         cd tools &&         make qt-faststart &&         cp qt-faststart ${PREFIX}/bin' returned a non-zero code: 2
```

**Comment by RazeLighter777** [comment]
@Artiume The command @nvllsvm used fails with the same error both on the current build (4.2.1) as well as 4.3, so this error isn't new.

**Comment by andrewrabert** [comment]
Blocked by https://github.com/jellyfin/jellyfin-ffmpeg/issues/44

**Comment by joshuaboniface** [comment]
#44 should be OK now that 4.3 is in, let's see how it looks now @nvllsvm @Artiume

**Comment by joshuaboniface** [comment]
Looks like this particular issue is fixed, but now the dav1d additions are causing some issues. Taking a look.

**Comment by joshuaboniface** [comment]
OK there's a bunch of strange merge conflicts when I try to rebase off this PR to push to it. I've made a new branch for this and will push to a new PR.

**Pull request closed without merging**
