### PR TITLE
New ffmpeg upstream version 4.4

### PR DESCRIPTION
**Pull request by nyanmisaka**
- New upstream version 4.4 (feat. AV1 HWA in DXVA/Intel/Nvidia)
- Support for Ubuntu hirsute 21.04
- Add BT.2390 algorithm to opencl tonemap
- Fix peak detection in opencl tonemap
- Add cuda tonemap impl
- NVDEC AV1 HW decoding
(**Minimum required driver versions:
Linux: 455.28 or newer
Windows: 456.71 or newer**)

Try it down below(other changes in jellyfin is needed):
https://drive.google.com/drive/folders/1u13Ot4A0YySraS_7y06XwfErj7W0NUIO?usp=sharing

### CODE REVIEW

**Comment by EraYaN** [comment]
I suppose we don't really need to review the code right?

**Review by EraYaN — APPROVED** [review]
Looked at the updated patches, looks good to me. I can't say I understand some of the algorithm stuff but I assume that has been tested.

**Comment by nyanmisaka** [comment]
Sure. Tested on GTX 1650, GTX 1050, HD 630 and Vega 64.

BT.2390 Algorithms and de/linearizer are pulled from mpv/libplacebo and zscale.

**Comment by EraYaN** [comment]
@jellyfin/core Probably needs to review + merge this one.

**Comment by nyanmisaka** [comment]
Note that changes made in jellyfin PR is also backward compatible to older version of jellyfin-ffmpeg.

**Review by joshuaboniface — APPROVED** [review]

**Pull request merged**
